healthCheck:
  handler: library/functions/server.healthCheck
  events:
    - http:
        path: /__health
        method: get
        cors: true

resetAll:
  handler: library/functions/server.resetAll

performPairing:
  handler: library/functions/pairing.pair
  events:
    - schedule: rate(10 minutes)

processTwilio:
  handler: library/functions/messaging.process
  events:
    - http:
        path: twilio
        method: post
        cors: true

testTwilio:
  handler: library/functions/test.send
  events:
    - http:
        path: testTwilio
        method: post
        cors: true
