healthCheck:
  handler: library/functions/server.healthCheck
  events:
    - http:
        path: /__health
        method: get
        cors: true

performPairing:
  handler: library/functions/pairing.pair
  events:
    - schedule: rate(10 minute)

processTwilio:
  handler: library/functions/messaging.process
  events:
    - http:
        path: twilio
        method: post
        cors: true
